"""version2

Revision ID: c6c01f143819
Revises: 33e6f7baeb04
Create Date: 2022-11-14 21:13:19.602593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c01f143819'
down_revision = '33e6f7baeb04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
